export { default as ClassesDropdown } from '@/pages/common/dropdowns/class/classes-dropdown/ClassesDropdown.vue'
export { default as SubjectsDropdown } from '@/pages/common/dropdowns/subject/subjects-dropdown/SubjectsDropdown.vue'
export { default as DifficultyDropdown } from '@/pages/common/dropdowns/olympiad-tasks//difficulty-dropdown/DifficultyDropdown.vue'
export { default as StatusDropdown } from '@/pages/common/dropdowns/olympiad-tasks/status-dropdown/StatusDropdown.vue'
export { default as TypeDropdown } from '@/pages/common/dropdowns/olympiad-tasks/type-dropdown/TypeDropdown.vue'
export { default as LanguageDropdown } from '@/pages/common/dropdowns/olympiad-tasks/language-dropdown/LanguageDropdown.vue'
export { default as TagsDropdown } from '@/pages/bank/olympiad-tasks/list/parts/tasks-filter/parts/tags-dropdown/TagsDropdown.vue'
