export { default as ClassesDropdown } from '@/pages/common/dropdowns/class/ClassesDropdown.vue'
export { default as SubjectsDropdown } from '@/pages/common/dropdowns/subject/SubjectsDropdown.vue'
export { default as DifficultyDropdown } from '@/pages/common/dropdowns/bank/test-tasks/difficulty-dropdown/DifficultyDropdown.vue'
export { default as ThemeDropdown } from '@/pages/common/dropdowns/themes-list/ThemeDropdown.vue'
export { default as StatusDropdown } from '@/pages/common/dropdowns/bank/test-tasks/status-dropdown/StatusDropdown.vue'
export { default as TypeDropdown } from '@/pages/common/dropdowns/bank/test-tasks/type-dropdown/TypeDropdown.vue'
export { default as LanguageDropdown } from '@/pages/common/dropdowns/bank/test-tasks/language-dropdown/LanguageDropdown.vue'
export { default as TagsDropdown } from '@/pages/bank/test-tasks/list/parts/test-tasks-filter/parts/tags-dropdown/TagsDropdown.vue'
